[project]
name = "bn-typed"
version = "0.1.1"
description = "Bottleneck stubs for type checks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.6",
]
[tool.setuptools.package-data]
"src" = ["py.typed"]
